language: node_js
before_install: npm prune
before_cache: npm prune
node_js:
- '4'
script: npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: npm run gh_deploy
  on:
    branch: master
    repo: craft-ai/HomeTogether
env:
  global:
  - CRAFT_URL=https://beta.craft.ai
  - CRAFT_OWNER=stanley_kubick
  - secure: ufDDJcd6XR4cuym3UvuQ/fC8kLPiRApTCcgJTm8gOupoRmH7KPG98neq/waDFUGhlrn/T3oXb+etwJZunqO36+t5rXW9WLoUNbkoGQOaSuziG8C4KO/JQJioiOzNgx/Rt2nNaNhn1vv59wNTs1zZXGnff7gh9C2ZYKuUiYGE1cBbPjHuu9nUoCdo05rLonDfqjcJ1EGGFHtcu0U45P6u9zAMgt0zBrQXvFUAKbDyn65hGyv/f9YgYgKKcXq3+Zkv7RO6RN3CXXHxFqdP2gLua44OOXck3Rfji3v4EKWGxAuH8NEAwhEMEGPgKK39+UhCgupX4C5IHxN+k2CSR0OwieFUIeNrcmlbVwv27RBbnD1mQa7pGo3Y37A4CM4FWkrDnyUMuYne2+JPLnCst0SOyPYOGsZViGkJnJ+/kqImqG0iQu4Vdb+lKLjDJxpatYi8eN8ojDIgD68TzPNRKl34pngx0lquRc6q/Bz2cwpsOV6xpkQ21Zt3yiB3yKGM08mCmNeiDMlj0AIYSK24tV3mw4swSEVedXfTnqgDwTRCuiztPMF3f6K2B6dolIcMefJ5RncmBmQtUZmDcNHYfuBCD47tI4kQysI08BNlpbbRWbKVHHGMnRwy9Z4fQ1zFJS159Pdphyg0JX1UnUjZgSmn687aR09OK5baTxJcDHKSW4o=
  - secure: ObgEq2YWmqwRlU5ZuHs7KWO38DH/RxubuIoNJKcvdC69yo8duGF6QaIyuKow+JvO30R+TyRQ2EywvqZ4ewkvsCJii3b0MgTaVWpCPnW+9r0KTSCLM84Sz88dPEJ1oFKlRvnqBVQfWEuC/3KdY+O3FvGUIs+Tq3mWpuX1BdkrQVUzZ6N5dQoUKIwCpstzJNzcSFWKdiCDyDghaKXqa+/PpBgz7tdL3+2ETctqXUPocay7Tq2B0ge1OuCo78lNzGXBEsgEHedrHEUGIw2kCbDiHNyz+6bWsEvTg0z4cYcxAwUP3LiJmfEzEijQi+dURGzmwciSbLQDV/ghM4xzjWHoMKBqDvv0k3m5rdNjr+FlDBoDSxDt+Q8WuvvdbD+YlmMj9rtCFpFyQ/r2LGzldIFVQK0a/hSfnqwF5g0q5hWSd5skv1Vz8aqpTGxK9QLtjggdnYGana1RA6kKDH0P6BDQsTkaEgDvFCrevX9kpJpvihRMSAcVNA8bXcl1Dh2VRZQwTSSEDekvauSnHlQMpqKJruFj4bw/4scnL2jUc36fb/Pj8B5d1f+D8dX6YnzUbNb8VBy+XyoKaHtZfNvFny+Qaq52bUDKn++1MLQgJahv6UnzVBoAxsTGt3YAamkCj3EgswUC9aTBXjyMfuLxTt2aYk1IfSnogyksVsI6o6pFoqg=
