language: node_js
before_install: npm prune
before_cache: npm prune
node_js:
- '4'
script: npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: npm run gh_deploy
  on:
    branch: master
    repo: craft-ai/HomeTogether
env:
  global:
  - CRAFT_URL=https://beta.craft.ai
  - CRAFT_OWNER=stanley_kubick
  - secure: ah+6bpjPQfpLxbGnBNXZVSilQlvP9NJPksUE4KI0TtVZJxp8xVvTJAZQnmVf9FbLR2ObLShkk3ZUn1lKl2xmZ6VrkmM7oZoH88/Ja2mj8V/hur03zdOnmbMAxUGOmaYp1Cbbjd6m85+mVVk7Vysc9n2AdgcPPYbHjCiw5j+zSgVnnUmpl5F4GIPcGgeV5qjeVNjjsS/7gtPgfQkavFL9RAahkg+c7eKESvam/HQXN+5KfM8j/NExFL/YOQSRUv0/fllblNuFe/zkpC+2mHE3zHd+Kvkdq2hVniKzANvx1PGoVI0nTBIL9zzLYgEb6d2P3qSd3ol1OrVnfFiZGU4nRyfth4fqOM8ktQOIS7clCYGcA8rwfIY/fGOlZF8rhx9X60x21BguRUoO7iSedP6U4/z61jwgkz5QKZJGtsCuCULEBdEbgpDxU0VCWk+tqGevKTOEH8pD6vEIc2U35RGuuXZketOvZz8+DGjh+uxErva1sIIc3drLLxnHn0t6EhHgJcYK76CsQqFNwVhffyRrdORtgR4rqUo1TseoYSv5X1Wc9zkzi+i0MBUoQ0WhAmhArOfzLqnimVD+XbINNBTOkEFiPS++NkEHgT26HGQCbuniwTw9qzv2CttqjdzfieentEbPVsB6dmm774TaomOxLK6wcKcqcCMoxqvhemNcK2c=
  - secure: G4DYSaED8UZS0Mjdo9S++OAFzE/uoz4kbBnUX08znscom4OFMfCtBeLmNgeKOGLJTehTBxnCa/FwHZXdND+cKw9RAw4NKstEbpr22zmCFDX8Vss2lfWbk5FvvHsvNtF0W7y9PJnV2sxLXmMxg7Wqf1+Q8J0IBw+BgjCvEkBm181JBLzfqmeRjFmfwAzvY+5YieRwmUW8CLft7WWo56TpQA6zmujXRJYFoIZTL0T04tmU5avruhsfIfnrEpXYMzfG8c+S5sl6qsn5vyW7v/wOFiUcHpNl9ClpzQQjRK8i5TTTE7lwNph8GTUyvAWcFn1G47nH4Xomxr/p10ZnQvFyQ9QREdgdS4zNNZivfVfOsYUJyKtQWv1lbfOzwHtS0ZpVQQDNabOaXAUGHRKxEtOcnEw46gvtoW8EUw6BT28FG5AwpfVoZcB4GpFDMiQwtM8iLFOZcv2hvxzO/Tsb+nf60HYVCjrWGcQgJ/iTuVUtURHjSTx6Sh7IGOZRpYt6WnRAYMJHvT3GrT+ZiGA5s7wPzS9cSy0PDwA2SzfVQAT62aO9G2Qm+/eQLyzERBoWS6ijo4t8hsaxK5W8R8l0iHOyz2csbFkTZHa4oF0vUgGppJD6QN2Ul9c7IyH9w8fxMfBJwhDiy8ngtogkucPVYyyXYM+moDJpbKCALh268B4aeT4=
  - secure: GIhLB5SjuLicRrdFq9bCeBfLPZ9FrVP3APFt4sohSRq3orZYRrqMSh4LEZIX8jnEbDKca5nQSDf4St1vKZabwhh0jhG82pTXl27nGDR7EI+Q5NpPFrDRWnJ7t8J/7KYj8BbUPHVoAYesqOlHR5CLYgzTcSkOyBzWB1q1zSdZ7bDWwe3AFBFLou+uH9FzNkbKzGiCrogHu0KNpymwVwozbZVeov1cJPU4ttwBv5ZiQJ4E3wyIs/3v5TReijKr8FUrTH8+/bywXfxFpoRmEW5Z/huM+G62nkfrbAj3ibPbXmzJsaOmk7pNfZsxfRZPcdauBQ/SpCjFJ5Em4oZK2kf963zZ7jcV2WbSZCcegi7zFD+Ohz3ZkrAqE+P9wPFXB+7pDRvCfbusY638E+NzzCcR6jfitLurnRQMSjJRXDItBiwDRuLb1MEfoS3fWwRS6MCsvw7VqkoNmThSDOw95SVqKnHKvfHPcMToF/uoAGD5wOs09zuCTy+vdspWIuiA0QbjLlbb94VHMDUfZWME/FxEXBzw9ZqmWkvlTiw1tl4+nMTjQJ5IVOGeHZZhA8rsuYbk7Okdn1DTgJfzjay8C2qcbKOeBx/S02E6/Vjz7SE09cVgrsjkKmHAMshog5JWZqQeE+cgorqN1bvhGO0WwxY05T59BwAlvqCukd4fbk/p6kk=
