language: node_js
before_install: npm prune
before_cache: npm prune
node_js:
  - "4"
script: npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: npm run gh_deploy
  on:
    branch: master
    repo: craft-ai/HomeTogether
env:
  global:
  - CRAFT_URL=https://beta.craft.ai
  - secure: YZZlxN9EfRFCg+Az2e9qUYldoLWEUFiCdt+XyTIfhuZESwDOk6thvEGO2S1l7RcycIgE1DozBBbNp7ZfZyibx8XXXKumsotjXImVxMC6LeBnE/GADv8CaC3WSfvUyarlt080o030TMnWqJEWpoBu+ksUhRZZZs4C3vwX77KQs9//0ShuG2g8aA17xSfY5EVgsrWdnUwyW4k+yH2O/bEeNQ+jxIX0UN97TrKGXU6INzZp7fYMMi9DtfNIDNctONo+ZnrZW5A5FlT92aNefwTZMUi9etkLaOyZsQqHYS2qSNMhmWgWdpZkAnfo78SJPmWnFggCV6qbMo8Q7CCFVk39PPkJyckZL5tSnv2ElNC9stSvqTgqVuAjZIDLLYG0qQsYBuhb1SVUw84vxhJkd9x1lbYS7pxV+yEsDnC1dVa02fYZ4JkLY1wEk9JYh1H7Hlid6MhsgM3ntOsokIRg5k/q2LW2W0Z6HR76wMMqyUV64yR/chf1d9zJRtQJyeM97fplNGFCxHiau6S5nvHpQCka63YglbGwtkgfLZp9NKyk4r57oFYILchDQ2YWPNKnjJl8lluzcPCddFWCmr1aJMLoZTMSBTT9ML2tUjDrke94KpONKJhgerMOMXxUp5mfHtMBJD+bUKJNM3CNA+2f1FqAw/r9NbS7STf0U2qjJFglnzY=
  - secure: FMM03WiA05EQMj2wi2MZTWVqieUbYt2Jb0Tjxgn85gBc0HYxq7xYGJ5MUEdzOhb6jm6VrDqqzbNdu4CzZipLUwSAzxSp07XoUn/cbWxCvdxewRsOgJjSyriuAWnz1po11nM3BBKQNJvrGfya0TK+/prLdB8elZ3ziDo05wYQjGSzlTJRRpkG71UYjVo0+ieR3uvdemrFpj6uDlf4+iElsNDG3xIbdyr/zb1qFX+deBvndr2y1RGLp3UL2Ue+/5lR2iT8PbG9JNqt5iXmqD2KkvWxQdt4CszPBeRA8ymhx7hSdYiS0oVmTUCf/FtxuBt+eZ0KMfifRufghVr8U+FyzvhtteOkopx6ECRV8EXPlmuT63VCSqnyREw9FyyWoJmJtBWSWBNd8UqQUGWySlXthKFd3xK4ZLy6bx0kN2RCi+pl7MMYKaP+Epc8mA4QVwo/6aXpsB9njkDREV8sbZNTCtRVUahOlVaYcACjlnmRm8o+xNW6kbEHpq9EK8hTYT8/WHILLl99sdhpRXO/s5+tjUA56cWoVds83sHIpJq66tWToJCei1Wnhp8ngouMdYxwRGTYWClq5YGrp5KMRK33LlTRlMBW4lsHNlG4y4FPzl2+X5AtFxc+6H9wJ6RubuAL1G3zNfrAYg+JK0wVUbS8IiIulCL3vk2juu6RsV4xyn8=
